  generate-report:
    name: Generate Allure report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Setup Java (required by Allure)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Allure CLI
        run: |
          ALLURE_VERSION=2.32.0
          wget -q https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
          sudo tar -zxf allure-${ALLURE_VERSION}.tgz -C /opt/
          sudo ln -sf /opt/allure-${ALLURE_VERSION}/bin/allure /usr/bin/allure
          allure --version

      - name: Download allure-results from tests job
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Check if gh-pages branch exists
        id: gh
        run: |
          if git ls-remote --exit-code --heads https://github.com/${{ github.repository }} gh-pages > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout gh-pages for history (optional)
        if: steps.gh.outputs.exists == 'true'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1
          persist-credentials: false

      - name: Reuse Allure history
        run: |
          if [ -d gh-pages/history ]; then
            echo "Copying previous history..."
            mkdir -p allure-results/history
            cp -R gh-pages/history/* allure-results/history/ || true
          else
            echo "No previous history found."
          fi

      - name: Generate report to _site
        run: |
          rm -rf _site
          allure generate -c allure-results -o _site
          test -d _site && echo "Allure report generated."

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 7
